# Nombre de la automatización que verás en GitHub
name: Desplegar Sitio Web en Hosting

# Define el evento que dispara esta automatización
on:
  # Se ejecutará cada vez que hagas 'push'
  push:
    # Específicamente a la rama 'main'
    branches:
      - main

# Define los trabajos (tareas) que se van a ejecutar
jobs:
  deploy:
    # Usa una máquina virtual de Ubuntu para ejecutar los pasos
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Descarga el código de tu repositorio a la máquina virtual
      - name: Checkout del código
        uses: actions/checkout@v4

      # Paso 2: Usa una herramienta pre-hecha para subir los archivos por FTP
      - name: Despliegue con FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          # Usa el Secreto que creaste para el servidor
          server: ${{ secrets.FTP_SERVER }}
          # Usa el Secreto que creaste para el usuario
          username: ${{ secrets.FTP_USERNAME }}
          # Usa el Secreto que creaste para la contraseña
          password: ${{ secrets.FTP_PASSWORD }}
          # El directorio en tu hosting donde se subirán los archivos.
          # ¡¡¡IMPORTANTE!!! Revisa que '/public_html/' sea la carpeta correcta para ti.
          server-dir: /